# @no
GET https://mirror.ghproxy.com/https://raw.githubusercontent.com/gaotianliuyun/gao/master/0821.json
Accept: application/json

### 内嵌服务器-测试
GET http://localhost:9978/

###
GET http://localhost:9978/proxy?do=ck&do=it

###
GET http://127.0.0.1:9978/proxy?do=ali&type=video&cate=open&shareId=5CNb1zzo7z9&fileId=6572dcc537aa2f73e51e499d9a14280cdcda9eaa


###
GET http://localhost:9978/test

###
# @no-redirect
GET http://127.0.0.1:9978/proxy?do=ali&type=video&cate=open&shareId=y16XnvQgLq3&fileId=6347a7c232ce90959c634c5b83d93b0622577f21

### 提示消息
GET https://127.0.0.1:9978/postMsg?msg=我是1112

###
POST http://cj.lziapi.com/api.php/provide/vod
Content-Type: application/json

{
  "wd":"海绵宝宝",
  "pg": "1"

}


###
POST https://exservice.12306.cn/lxgjadmin/bs-service-pre/reception/submit
Content-Type: application/json

{
  "ACCOUNT_PARAM":[
    {
      "VALUE":"SIGN",
      "KEY":"0af211cdc4973845628ac6f81f8b481b"
    },
    {
      "VALUE":"wzl_ai_fs",
      "KEY":"PRODUCT_ID"
    }
  ],
  "ID":"2100000003480798",
  "ORDER_TIME":"2023-02-22 09:31:53",
  "PHONE_NUMBER":"18652056535",
  "TRADE_ID":"6000000713222079"
}

