name: set-tag
on:
  workflow_call:
    outputs:
      tag:
        description: "latest tag"
        value: ${{jobs.set-tag.outputs.output1}}
      lastTag:
        description: "last tag"
        value: ${{jobs.set-tag.outputs.output2}}

jobs:
  set-tag:
    name: set-tag
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.tag.outputs.tag }}
      output2: ${{ steps.last-tag.outputs.lastTag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      - id: last-tag
        run: echo "lastTag=$(git tag --sort=-creatordate | sed -n '2p')" >> $GITHUB_OUTPUT
